"""add_font_standards_table

Revision ID: 0ed239e13499
Revises: 683ad041d597
Create Date: 2026-07-04 22:43:28.556854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed239e13499'
down_revision: Union[str, None] = '683ad041d597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('font_standards',
    sa.Column('char', sa.String(), nullable=False),
    sa.Column('font_id', sa.String(), nullable=False),
    sa.Column('standard_height', sa.Integer(), nullable=False),
    sa.Column('standard_width', sa.Integer(), nullable=False),
    sa.Column('aspect_ratio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('char', 'font_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('font_standards')
    # ### end Alembic commands ###
