"""add stroke_standards table

Revision ID: 683ad041d597
Revises: 726441809008
Create Date: 2026-06-25 21:10:53.926646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683ad041d597'
down_revision: Union[str, None] = '726441809008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stroke_standards',
    sa.Column('char', sa.String(), nullable=False),
    sa.Column('expected_sequence', sa.JSON(), nullable=False),
    sa.Column('standard_height', sa.Integer(), nullable=True),
    sa.Column('standard_width', sa.Integer(), nullable=True),
    sa.Column('standard_spacing', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('char')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stroke_standards')
    # ### end Alembic commands ###
