"""add_s3_image_url_to_image_analysis_results

Revision ID: 8cc78a9d44f7
Revises: 0ed239e13499
Create Date: 2026-07-05 12:21:14.460911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc78a9d44f7'
down_revision: Union[str, None] = '0ed239e13499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_analysis_results', sa.Column('s3_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_analysis_results', 's3_image_url')
    # ### end Alembic commands ###
