// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe4XSSPNXgXziUDTnUQnodRbvTG433i_M',
    appId: '1:163844884781:web:5379dbc65233c8b7882ba4',
    messagingSenderId: '163844884781',
    projectId: 'hanium-handwriting',
    authDomain: 'hanium-handwriting.firebaseapp.com',
    storageBucket: 'hanium-handwriting.firebasestorage.app',
    measurementId: 'G-P441WRF4DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCthn2fR-VsZaImhDhx6Kq5FdW2-xBHzQA',
    appId: '1:163844884781:android:5ea994ac0b9f37d0882ba4',
    messagingSenderId: '163844884781',
    projectId: 'hanium-handwriting',
    storageBucket: 'hanium-handwriting.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwq9R2AFODTBYsUBrSRhyUEDMPpDiL_EY',
    appId: '1:163844884781:ios:cc55aec8f9e43c83882ba4',
    messagingSenderId: '163844884781',
    projectId: 'hanium-handwriting',
    storageBucket: 'hanium-handwriting.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwq9R2AFODTBYsUBrSRhyUEDMPpDiL_EY',
    appId: '1:163844884781:ios:cc55aec8f9e43c83882ba4',
    messagingSenderId: '163844884781',
    projectId: 'hanium-handwriting',
    storageBucket: 'hanium-handwriting.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe4XSSPNXgXziUDTnUQnodRbvTG433i_M',
    appId: '1:163844884781:web:14b72ffa4b0e64fe882ba4',
    messagingSenderId: '163844884781',
    projectId: 'hanium-handwriting',
    authDomain: 'hanium-handwriting.firebaseapp.com',
    storageBucket: 'hanium-handwriting.firebasestorage.app',
    measurementId: 'G-E2C9QYRVD2',
  );
}
